# SFT Pipeline with Post-Processing Configuration
# This configuration demonstrates SFT training with Hub upload and GGUF conversion

# Model configuration
model_name_or_path: "microsoft/DialoGPT-medium"
use_auth_token: false
trust_remote_code: false
torch_dtype: "float16"

# Pipeline configuration
output_dir: "./outputs/sft_with_postprocessing"
stages:
  - "sft"

# Global settings
save_final_model: true
cleanup_intermediate: false
log_level: "INFO"

# Post-processing configuration - ENABLED
# Hugging Face Hub upload
push_to_hub: true
hub_repo_id: "your-username/my-fine-tuned-model"  # CHANGE THIS to your actual repo
hub_commit_message: "Upload fine-tuned model with LoRA adapters"
hub_private: false  # Set to true for private repositories
hub_token: null  # Set via HF_TOKEN environment variable
push_adapter_only: true  # Upload only LoRA adapters (recommended for SFT)

# GGUF conversion for Ollama compatibility
convert_to_gguf: true
gguf_quantization: "q4_0"  # Good balance of size and quality
gguf_output_path: "./outputs/sft_with_postprocessing/model_q4_0.gguf"

# Stage-specific configurations
stage_configs:
  sft:
    # Dataset configuration
    dataset_name_or_path: "examples/sample_data.jsonl"
    max_seq_length: 2048
    instruction_template: "### Instruction:\n{instruction}\n\n### Response:\n{response}"
    validation_split: 0.1
    auto_detect_format: true
    
    # Quantization configuration
    use_4bit: true
    use_8bit: false
    bnb_4bit_compute_dtype: "float16"
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: true
    
    # LoRA configuration
    lora_r: 16
    lora_alpha: 32
    lora_dropout: 0.1
    lora_target_modules: null  # Auto-detect
    lora_bias: "none"
    
    # Training configuration
    num_train_epochs: 3
    per_device_train_batch_size: 4
    per_device_eval_batch_size: 4
    gradient_accumulation_steps: 1
    learning_rate: 2e-4
    weight_decay: 0.001
    warmup_ratio: 0.03
    lr_scheduler_type: "cosine"
    logging_steps: 10
    save_steps: 500
    eval_steps: 500
    save_total_limit: 3
    load_best_model_at_end: true
    metric_for_best_model: "eval_loss"
    greater_is_better: false
    
    # Logging
    use_wandb: false
    wandb_project: "lmpipeline"
