# SFT-Only Pipeline Configuration
# This configuration runs only the SFT stage for backward compatibility

# Model configuration
model_name_or_path: "microsoft/DialoGPT-medium"
use_auth_token: false
trust_remote_code: false
torch_dtype: "float16"

# Pipeline configuration
output_dir: "./outputs/sft_only"
stages:
  - "sft"

# Global settings
save_final_model: true
cleanup_intermediate: false
log_level: "INFO"

# Stage-specific configurations
stage_configs:
  sft:
    # Dataset configuration
    dataset_name_or_path: "examples/sample_data.jsonl"
    max_seq_length: 2048
    instruction_template: "### Instruction:\n{instruction}\n\n### Response:\n{response}"
    validation_split: 0.1
    auto_detect_format: true
    
    # Quantization configuration
    use_4bit: true
    use_8bit: false
    bnb_4bit_compute_dtype: "float16"
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: true
    
    # LoRA configuration
    lora_r: 16
    lora_alpha: 32
    lora_dropout: 0.1
    lora_target_modules: null  # Auto-detect
    lora_bias: "none"
    
    # Training configuration
    num_train_epochs: 3
    per_device_train_batch_size: 4
    per_device_eval_batch_size: 4
    gradient_accumulation_steps: 1
    learning_rate: 2e-4
    weight_decay: 0.001
    warmup_ratio: 0.03
    lr_scheduler_type: "cosine"
    logging_steps: 10
    save_steps: 500
    eval_steps: 500
    save_total_limit: 3
    load_best_model_at_end: true
    metric_for_best_model: "eval_loss"
    greater_is_better: false
    
    # Logging
    use_wandb: false
    wandb_project: "lmpipeline"
